### ISSUE TITLE
Flag documentation

### ISSUE THREAD

**Issue by mac3747** [expel-io/pyexclient#56]
The flag [documentation](https://pyexclient.readthedocs.io/en/latest/examples/examples.html?highlight=flag#flag) seems to be incorrect. 

Example from docs shows:
```
for inv in x.investigations.search(flag("search", "ransomware"), limit(1)):
    print(f"Incident related to ransomware: {inv.title}")
```

but when that is ran I get a TypeError as shown below:
```
TypeError                                 Traceback (most recent call last)
/var/folders/g9/xmhkp1tx40n1xh915v__r8nr0000gp/T/ipykernel_8667/2127280873.py in <module>
----> 1 for inv in xc.investigations.search(flag("search", "ransomware")):
      2     print(f"Incident related to ransomware: {inv.title}")

TypeError: __init__() takes 2 positional arguments but 3 were given
```

Based on a [test case ](https://github.com/expel-io/pyexclient/blob/main/tests/test_workbench.py#L221-L225)I found in the repo. It looks like the example should look more like this:

```

for inv in xc.investigations.search(search=flag("ransomware")):
    print(f"Incident related to ransomware: {inv.title}")

```
The above example works in my case.

Meta:
Python Version: Python 3.8.9
Package version:
```
Name: pyexclient
Version: 0.0.9
....
````

**Comment by dawhalen** [comment]
Hey @mac3747 thank you for reporting this! We've got a pull request open to fix the documentation and will get that pushed out soon.

**Comment by dawhalen** [comment]
Documentation has been updated, closing this issue
